# vagrant/config/domains.yml
domains:
  - host: gitlab.demo.pathops.io
    upstream: 192.168.56.12
    port: 80
  - host: jenkins.demo.pathops.io
    upstream: 192.168.56.13
    port: 8080
  - host: keycloak.demo.pathops.io
    upstream: 192.168.56.14
    port: 80
  - host: argocd.demo.pathops.io
    upstream: 192.168.56.16
    port: 80
