# vagrant/config/vms.yml
project:
  name: pathops-demo
  ubuntu_box: "bento/ubuntu-24.04"   # podés cambiarlo por ubuntu/jammy64 si preferís
  hostonly_network: "vboxnet0"
  ip_cidr: "192.168.56.0/21"
  gateway: "192.168.56.1"   # opcional: no es necesario si no seteás ruta default en las VMs
  nameservers: ["1.1.1.1", "8.8.8.8"]

vms:
  - name: vm01-edge
    hostname: edge
    ip: 192.168.56.11
    lan_ip: 192.168.1.90
    cpus: 1
    memory: 1024
    disk_gb: 20 
    roles: ["edge"]

  - name: vm02-gitlab
    hostname: gitlab
    ip: 192.168.56.12
    cpus: 2
    memory: 4096
    disk_gb: 80
    roles: ["gitlab"]

  - name: vm03-jenkins
    hostname: jenkins
    ip: 192.168.56.13
    cpus: 2
    memory: 4096
    disk_gb: 60
    roles: ["jenkins", "docker"]

  - name: vm04-k8s-shared
    hostname: k8s-shared
    ip: 192.168.56.14
    cpus: 4
    memory: 16384
    disk_gb: 200
    roles: ["k8s_shared", "microk8s"]

  - name: vm05-k8s-control-plane
    hostname: k8s-cp
    ip: 192.168.56.15
    cpus: 2
    memory: 4096
    disk_gb: 60
    roles: ["k8s_cp", "microk8s"]

  - name: vm06-k8s-apps
    hostname: k8s-apps
    ip: 192.168.56.16
    cpus: 4
    memory: 16384
    disk_gb: 100
    roles: ["k8s_apps", "microk8s", "observability"]
