$ANSIBLE_VAULT;1.1;AES256
61386336376263653664333864376434343561346262303039353334316164613033303333396131
3466386139313766633135643632663534656665306234370a633232393831636166383630343739
34386437636432646232386530346139633134373362663431396633336537366630306130373330
3234383061343166640a306234316332663161363530353662656236346665633734376663323036
62623130656366643766363631303635613734663936323836326138613464386330623034653134
32316632336363613831303466396438613436646433616337666531373865396366376635386463
32386533383732626433336339363164383733616136663864623337626636343764353366653031
62346331646666343430613862373034386131356362353533343365393233646265653361353939
33386531613431376662636665643735333935343764356436373235666139633236343565313332
33343838623737316261633335343231623432386234376330366438303539366562633062653930
30353864383464623435643666646633373962363661373235616630313633333031643465396136
66333037613063363731
