$ANSIBLE_VAULT;1.1;AES256
64616566613938343562373863323463643734306134326330386634383261656237646633646139
6336653535313863313766666436376531343534663863300a653661383334616461616133326239
34316166646534386663383230663262316633636531303530306166613862643833353635306533
6630313961336365380a366339386461316333653132333061633232346662303232643765626661
63633764363535376433376435356639373838333533653833636134326239396663373962656532
36353139643861313063376436353336323261613666663930663332326134353661643961316335
30623066383131373238636235663866656238646235363238393330616562646563323438613132
32643364336136343538363237326538333732623565353561653432633065356530653436353538
3432
