$ANSIBLE_VAULT;1.1;AES256
36303936303861613336316430616631313938363938383864613962646262316531643762353964
3235376536663039653433303962316364303163653738350a353562663433363165333962303535
61363733356539353965303836326539616361366434643637323061663130346537333938343631
3163396664346133310a616531623563653966623133663861353938656230643136373639333431
38346531383561373132663039313330326638636639633839653961646131373439646435356333
63366563393864386632633166366534643366653134636365636663343639613430383537636330
656634633764373363333066383334313464
