---
- name: Install and configure GitLab CE (Open Source)
  hosts: gitlab
  become: true

  vars_files:
    - ../group_vars/all.yml
    - ../host_vars/{{ inventory_hostname }}.yml
    - ../host_vars/{{ inventory_hostname }}_vault.yml

  roles:
    - gitlab
