---
- name: Install and configure Jenkins + Docker
  hosts: jenkins
  become: true

  vars_files:
    - ../group_vars/all.yml
    - ../host_vars/{{ inventory_hostname }}.yml
    - ../host_vars/{{ inventory_hostname }}_vault.yml

  roles:
    - jenkins_docker