# ansible/playbooks/site.yml
- import_playbook: 00-base.yml
- import_playbook: 10-edge-nginx.yml
#- import_playbook: 20-gitlab.yml
#- import_playbook: 30-jenkins-docker.yml
#- import_playbook: 40-microk8s.yml
#- import_playbook: 50-k8s-shared.yml
#- import_playbook: 60-k8s-controlplane.yml
#- import_playbook: 70-k8s-apps.yml
#- import_playbook: 99-verify.yml
