# ansible/playbooks/site.yml
- import_playbook: base/main.yml
#- import_playbook: edge/main.yml
#- import_playbook: gitlab/main.yml
#- import_playbook: jenkins/main.yml
#- import_playbook: microk8s/main.yml
#- import_playbook: k8s-shared/main.yml
#- import_playbook: k8s-controlplane/main.yml
#- import_playbook: k8s-apps/main.yml
#- import_playbook: verify/main.yml
